### ISSUE TITLE
My language setting was right

### ISSUE THREAD

**Issue by MrBlasyMSK** [Muqsit/ChestShop#111]
For the last issue, is your plugin who dont register the lang of the items
![image](https://user-images.githubusercontent.com/85447029/160502984-6bdd403f-7884-454e-85be-5edf47932f41.png)

**Comment by Muqsit** [comment]
Once again, this has nothing to do with ChestShop. If you're experiencing that issue, you're likely experiencing it without ChestShop as well.

**Comment by MrBlasyMSK** [comment]
But you could add to register the language that is in the config for the blocks

**Comment by Muqsit** [comment]
I don't understand what you mean by that

**Comment by MrBlasyMSK** [comment]
To register the language in which the blocks are, and so that they appear with the default language of the config.

**Comment by Muqsit** [comment]
Well, I don't think that's possible since default item names are something PocketMine must handle. The only language translations that are provided are mostly for console and command output.

Most of pocketmine code is still primarily in English which is the root issue: https://github.com/pmmp/PocketMine-MP/blob/8cc7fb9dd9e03d223095c71d5b9c045f4f799733/src/block/BlockFactory.php#L490

**Comment by MrBlasyMSK** [comment]
Oh, then I didn't say anything, sorry.

**Comment by Muqsit** [comment]
As a workaround, you can set `item-button.name` in `category.yml` to `""` instead of `"&r{NAME}"`. Unsure if it'll work but this would only translate item names in the GUI but not in chat messages.

**Comment by MrBlasyMSK** [comment]
i will try

**Comment by MrBlasyMSK** [comment]
IT WORKS! Thx!
